import { relations } from 'drizzle-orm';
import { integer, pgTable, serial, text, timestamp, boolean, jsonb, pgEnum } from 'drizzle-orm/pg-core';

export const users = pgTable('users', {
  id: serial('id').primaryKey(),
  uid: text('uid').notNull().unique(), // Firebase Auth UID
  email: text('email').notNull(),
  name: text('name'),
  role: text('role').default('engineer'), // engineer, admin
  githubToken: text('github_token'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const statusEnum = pgEnum('incident_status', ['triggered', 'investigating', 'pending_approval', 'resolved', 'aborted']);
export const severityEnum = pgEnum('incident_severity', ['sev1', 'sev2', 'sev3']);

export const incidents = pgTable('incidents', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  description: text('description'),
  status: statusEnum('status').default('triggered').notNull(),
  severity: severityEnum('severity').default('sev2').notNull(),
  triggeredAt: timestamp('triggered_at').defaultNow().notNull(),
  resolvedAt: timestamp('resolved_at'),
  affectedServices: text('affected_services').array(),
  tags: text('tags').array().default([]),
  rootCauseId: integer('root_cause_id'), // Will be linked below
  report: jsonb('report'), // Structured report generated by agent
  assignedTeam: text('assigned_team'),
  assigneeId: integer('assignee_id').references(() => users.id),
  pagerdutyId: text('pagerduty_id'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
});

export const triageRules = pgTable('triage_rules', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  conditionField: text('condition_field').notNull(), // e.g., 'source', 'title', 'payload.service'
  conditionOperator: text('condition_operator').notNull(), // 'equals', 'contains'
  conditionValue: text('condition_value').notNull(),
  actionSeverity: severityEnum('action_severity'),
  actionTeam: text('action_team'),
  isActive: boolean('is_active').default(true).notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const rcaTemplates = pgTable('rca_templates', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  content: text('content').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const alerts = pgTable('alerts', {
  id: serial('id').primaryKey(),
  incidentId: integer('incident_id').references(() => incidents.id),
  source: text('source').notNull(), // PagerDuty, Datadog
  externalId: text('external_id'),
  title: text('title').notNull(),
  payload: jsonb('payload'),
  receivedAt: timestamp('received_at').defaultNow().notNull(),
});

export const rootCauses = pgTable('root_causes', {
  id: serial('id').primaryKey(),
  incidentId: integer('incident_id').references(() => incidents.id).notNull(),
  hypothesis: text('hypothesis').notNull(),
  evidence: jsonb('evidence').notNull(), // Citations, log lines, etc
  confidence: integer('confidence').notNull(), // 0-100
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// Any proposed remediation action
export const remediationActions = pgTable('remediation_actions', {
  id: serial('id').primaryKey(),
  incidentId: integer('incident_id').references(() => incidents.id).notNull(),
  description: text('description').notNull(),
  actionType: text('action_type').notNull(), // restart_service, rollback_deployment, etc
  actionPayload: jsonb('action_payload'),
  status: text('status').default('proposed').notNull(), // proposed, approved, rejected, executed, failed
  approvedBy: integer('approved_by').references(() => users.id),
  approvedAt: timestamp('approved_at'),
  executedAt: timestamp('executed_at'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

// System execution log for auditing
export const auditLogs = pgTable('audit_logs', {
  id: serial('id').primaryKey(),
  incidentId: integer('incident_id').references(() => incidents.id),
  userId: integer('user_id').references(() => users.id),
  action: text('action').notNull(),
  details: jsonb('details'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const comments = pgTable('comments', {
  id: serial('id').primaryKey(),
  incidentId: integer('incident_id').references(() => incidents.id).notNull(),
  userId: integer('user_id').references(() => users.id).notNull(),
  content: text('content').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});
